using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Linq;
using System.Text;

namespace DialogMaker.Core.Scripting.CodeAnalyzer
{
    [Generator]
    public class EnumHelperGenerator : IIncrementalGenerator
    {
        #region Controls

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var enumCandidates = context.SyntaxProvider.ForAttributeWithMetadataName(
                GenerateValuesAttributeName,
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: static (context, cancellationToken) => GetEnumInfo(context))
                .Where(static info => info is not null);

            context.RegisterSourceOutput(enumCandidates.Collect(), static (sourceContext, enums) =>
            {
                foreach (var info in enums)
                {
                    if (info == null)
                    {
                        continue;
                    }

                    var source = GenerateHelper(info);
                    var fileName = $"{info.Generator.EnumType.Name}Helper.g.cs";

                    if (info.Generator.Namespace != null)
                    {
                        fileName = $"{info.Generator.Namespace}." + fileName;
                    }

                    sourceContext.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
                }
            });
        }

        private static EnumInfo? GetEnumInfo(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetSymbol is not INamedTypeSymbol enumSymbol)
            {
                return null;
            }

            EnumHelperType type = EnumHelperType.Values;

            if (context.Attributes.Length > 0)
            {
                foreach (var attribute in context.Attributes)
                {
                    var fullName = attribute.AttributeClass?.FullName;
                    var constructor = attribute.ConstructorArguments;

                    if (fullName == null || 
                        constructor == null ||
                        !fullName.Contains(GenerateValuesAttributeName))
                    {
                        continue;
                    }
                    foreach (var arg in attribute.ConstructorArguments)
                    {
                        type = (EnumHelperType)Enum.ToObject(typeof(EnumHelperType), arg.Value);
                        break;
                    }
                }
            }

            return new(EnumInformationGenerator.Create(enumSymbol), type);
        }

        private static string GenerateHelper(EnumInfo info)
        {
            var generator = info.Generator;
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine();
            builder.AppendLine("#nullable enable");
            builder.AppendLine();

            var hasNamespace = !string.IsNullOrEmpty(generator.Namespace);

            if (hasNamespace)
            {
                builder.AppendLine($"namespace {generator.Namespace}");
                builder.AppendLine("{");
            }

            var indent = CodeGeneratorHelper.GetIndent(hasNamespace ? 1 : 0);

            if (info.Type == EnumHelperType.Full)
            {
                generator.WriteValueInfoDeclaration(builder, 1);
                builder.AppendLine();
            }

            builder.AppendLine($"{indent}/// <summary>");
            builder.AppendLine($"{indent}/// Helper for <see cref=\"{generator.Name}\"/> with {info.Type}");
            builder.AppendLine($"{indent}/// </summary>");
            builder.AppendLine($"{indent}public static class {generator.Name}Helper");
            builder.AppendLine($"{indent}{{");

            if (info.Type == EnumHelperType.Values)
            {
                generator.WriteValuesField(builder, 2, "Values");
            }
            else
            {
                generator.WriteValuesInfo(builder, 2, "Values");
            }
            
            builder.AppendLine($"{indent}}}");

            if (hasNamespace)
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        #endregion

        #region Constants

        private const string GenerateValuesAttributeName = "DialogMaker.Core.Scripting.CodeAnalyzer.GenerateInformationAttribute";

        #endregion

        #region Structs

        private sealed record EnumInfo(EnumInformationGenerator Generator, EnumHelperType Type);

        #endregion
    }
}
